# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
    inputs:
      version:
        description: Bump Version
        default: v1.0.0
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  echo-input:
   runs-on: ubuntu-latest
   steps:
    - name: Print Input
      run: echo input - ${{ github.event.inputs.version }}

