# This is a basic workflow to help you get started with Actions

name: temp

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Enter PR link (ex: https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1481/)"
        default: 
        required: true
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:   
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Print Input
      run: echo Running the PR builder for PR - ${{ github.event.inputs.version }}
    - name: Run PR builder
      id: my_id
      env:
        PR_LINK: ${{github.event.inputs.version}}
      run: |
        wget https://raw.githubusercontent.com/omindu/test/master/builder.sh
        bash builder.sh
    - name: Print Outout
      run: echo Reading ${REPO} And ${{steps.my_id.outputs.REPON}} values
