name: ubuntu-18.04-jdk-1.8

on:
  schedule:
  - cron: '*/15 * * * *'
   
jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
      with:
        ref: master      
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn clean install
